name: Main
on:
  push:
    paths:
      - 'object-service/**'

jobs:
  object-service-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kn and func
        run: |
            wget https://github.com/knative/client/releases/download/knative-v1.14.0/kn-linux-amd64
            mv kn-linux-amd64 kn
            chmod +x kn
            sudo mv kn /usr/local/bin/
            wget https://github.com/knative/func/releases/download/knative-v1.14.0/func_linux_amd64
            mv func_linux_amd64 kn-func
            chmod +x kn-func
            sudo mv kn-func /usr/local/bin/

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.MINDWM_TOKEN }} | docker login ghcr.io -u metacoma --password-stdin

      - name: Build and Push object-service
        run: |
          cd object-service
          kn func build --verbose --push -i ghcr.io/mindwm/kubernetes-context/object-service:latest


#          kn func build -r ghcr.io/mindwm/kubernetes-context
#          docker push ghcr.io/mindwm/kubernetes-context/object-service:latest
